language: python
dist: trusty
cache: pip

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - "TRAVIS_SPEEDUP_OPTS=--with-speedups"
  - "TRAVIS_SPEEDUP_OPTS=--without-speedups"

jobs:
  allow_failures:
    - python: "2.6"

addons:
  apt:
    packages:
      - libgeos-dev
      - python-numpy

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
  - pip install pip setuptools --upgrade
  - pip install --install-option="--no-cython-compile" cython
  - pip install --upgrade coveralls pytest-cov pytest>=3.8

install:
  - pip install -e .[test]
  - pip install coveralls

script: "py.test --cov shapely --cov-report term-missing ${TRAVIS_SPEEDUP_OPTS}"

after_success:
  - coveralls || echo "!! intermittent coveralls failure"
  
notifications:
    email: false
